apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# this variable is used in hack/generate_template.py to override the namespace
namespace: ${NAMESPACE}
resources:
- catalogsource.yaml
- namespace.yaml
- operatorgroup.yaml
- subscription.yaml
