apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: metrics-service
  namespace: system
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
  selector:
    control-plane: controller-manager
