apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: managed-node-metadata-operator
subjects:
  - kind: ServiceAccount
    name: managed-node-metadata-operator
    namespace: openshift-managed-node-metadata-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: managed-node-metadata-operator
